@startuml

title Monitor File Upload

actor User
participant PublicAPI
participant MonitorMgmt as MM
participant DB
participant Ambassador as Amb
participant Envoy
participant Telegraf

User -> PublicAPI: POST Monitor with file
PublicAPI -> MM: POST Monitor with file
MM -> DB: saves file as mediumblob in monitor table, creates bound monitor with hashes, renders template variables
MM -> AMB: bound monitor event
DB -> AMB: get bound monitor with hashes
AMB -> Envoy: send config op with hashes
Envoy -> AMB: if hashes dont match, request new zipfiles
AMB -> Envoy: send zip files
Envoy -> Envoy: unzip files

@enduml