@startuml

title Monitor File Upload/Delete

actor User
participant MonitorMgmt as MM
database DB
participant Ambassador as Amb
participant Envoy


User -> MM: POST Monitor with file
MM -> DB: saves file as mediumblob, creates bm with hashes, renders template vars
MM -> Amb: bound monitor event
DB -> Amb: get bound monitor with hashes
Amb -> Envoy: send config op with hashes
Envoy -> Amb: if hashes dont match, request new zipfiles
Amb -> Envoy: send zip files
Envoy -> Envoy: unzip files

@enduml