@startuml

actor user [
End User
]
actor salus_admin [
  Salus Admin
]
agent envoy [
  Envoy
]

database mysql [
  MySQL
]
boundary repose_auth [
  Repose
  Auth Service
]
boundary repose_public_api [
  Repose
  Public API
]
boundary repose_admin_api [
  Repose
  Admin API
]
agent kapacitor
agent kube_api [
  Kubernetes API
]
agent vault
database etcd
queue umb [
  UMB
]

agent public_api
agent admin_api

frame SalusBackendApps {
agent pm [
  Presence Monitor
]
agent auth [
  Auth Service
]
agent ambassador [
  Ambassador
]
agent evm [
  Event Engine Management
]
agent evi [
  Event Engine Ingest
]
agent rm [
  Resource Management
]
agent mm [
  Monitor Management
]
agent zw [
  Zone Watcher
]
agent acm [
  Agent Catalog Management
]
}

evm -down-> kapacitor
evm -down-> mysql
evm -down-> kube_api : calls

evi -down-> kapacitor
evi -down-^ umb
evi -down-> kube_api : calls

rm -down-^ umb
rm -down-> mysql

mm -down-# umb
mm -> rm : calls
mm -down-> mysql
mm -down-> etcd

pm -down-^ umb
pm -down-> etcd
pm -> rm : calls

zw -down-> etcd
zw -down-^ umb
zw -> mm : calls

envoy -down-> ambassador : gRPC over TLS
ambassador -down-> umb
ambassador -down-> etcd
ambassador -> vault
ambassador -> mm : calls
ambassador -> rm : calls

acm -> rm : calls
acm -> mysql
acm -> umb

envoy -down-> repose_auth : calls
repose_auth -down-> auth
auth -down-> vault

user -down-> repose_public_api
repose_public_api -down-> public_api
public_api -down-> etcd
public_api -down-> rm
public_api -down-> mm
public_api -down-> evm
public_api -down-> acm

salus_admin -down-> repose_admin_api
repose_admin_api -down-> admin_api
admin_api -down-> etcd
admin_api -down-> mm
admin_api -down-> rm
admin_api -down-> evm
admin_api -down-> pm
admin_api -down-> acm

@enduml